name: Python Flask CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      env:
        DB_SERVER: ${{ secrets.DB_SERVER }}
        DB_NAME: ${{ secrets.DB_NAME }}
      run: |
        export DATABASE_URL="DRIVER={ODBC Driver 17 for SQL Server};SERVER=${DB_SERVER};DATABASE=${DB_NAME};Trusted_Connection=yes;"
        PYTHONPATH=./ python -m pytest tests/
    - name: Lint with Flake8
      run: |
        pip install flake8
        flake8 .
