name: Python Flask CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2019-CU8-ubuntu-16.04
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: YourStrong!Passw0rd
        ports:
          - 1433:1433
        options: >-
          --health-cmd="sqlcmd -S localhost,1433 -U SA -P 'YourStrong!Passw0rd' -Q 'SELECT 1'"
          --health-interval=30s
          --health-timeout=10s
          --health-retries=10

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      env:
        DATABASE_URL: "Server=localhost,1433;Database=master;User ID=SA;Password=YourStrong!Passw0rd;"
      run: |
        pytest tests/
    - name: Lint with Flake8
      run: |
        pip install flake8
        flake8 .
    - name: Docker Logs
      if: failure()
      run: |
        docker logs sqlserver
